"""
Spine Project Packager

Packages complete Spine projects including JSON, atlas, images, and metadata
into a distributable ZIP file.
"""

from __future__ import annotations

import json
import zipfile
from pathlib import Path
from typing import Optional


def package_spine_project(
    spine_dir: Path,
    output_path: Optional[Path] = None,
    project_name: str = "character"
) -> Path:
    """
    Package a Spine project into a ZIP file.
    
    Args:
        spine_dir: Directory containing Spine files (.json, .atlas, .png)
        output_path: Optional path for output ZIP file
        project_name: Base name for the project
        
    Returns:
        Path to created ZIP file
    """
    if not spine_dir.exists():
        raise FileNotFoundError(f"Spine directory not found: {spine_dir}")
    
    if output_path is None:
        output_path = spine_dir / f"{project_name}_spine.zip"
    
    # Collect all project files
    files_to_package = []
    
    # Find JSON file
    json_files = list(spine_dir.glob("*.json"))
    if json_files:
        files_to_package.extend(json_files)
    
    # Find atlas file
    atlas_files = list(spine_dir.glob("*.atlas"))
    if atlas_files:
        files_to_package.extend(atlas_files)
    
    # Find PNG files
    png_files = list(spine_dir.glob("*.png"))
    if png_files:
        files_to_package.extend(png_files)
    
    if not files_to_package:
        raise ValueError(f"No Spine files found in {spine_dir}")
    
    # Create ZIP file
    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zipf:
        for file_path in files_to_package:
            if file_path.is_file() and file_path != output_path:
                # Add file with relative path
                arcname = file_path.name
                zipf.write(file_path, arcname)
        
        # Add README
        readme_content = f"""# {project_name} Spine Project

This package contains a complete Spine animation project.

## Contents

- `{project_name}.json` - Spine skeleton and animation data
- `{project_name}.atlas` - Texture atlas definition
- `{project_name}.png` - Texture atlas image

## Usage

1. Open Spine Editor (https://esotericsoftware.com/)
2. File > Import Data
3. Select the .json file
4. The character with all animations will be loaded

## Animations

This project includes the following animations:
- idle: Breathing/standing idle animation
- walk: Walking cycle
- jump: Jumping animation
- wave_r: Wave with right hand
- wave_l: Wave with left hand

## Generated by imgGen Spine2D Animation System
"""
        zipf.writestr("README.txt", readme_content)
    
    return output_path


def create_spine_metadata(
    spine_dir: Path,
    character_name: str,
    animations: list[str],
    metadata_path: Optional[Path] = None
) -> Path:
    """
    Create a metadata JSON file for the Spine project.
    
    Args:
        spine_dir: Directory containing Spine files
        character_name: Name of the character
        animations: List of animation names
        metadata_path: Optional path for metadata file
        
    Returns:
        Path to created metadata file
    """
    if metadata_path is None:
        metadata_path = spine_dir / "metadata.json"
    
    metadata = {
        "character_name": character_name,
        "spine_version": "4.1.00",
        "animations": animations,
        "created_by": "imgGen Spine2D Animation System",
        "files": {
            "skeleton": f"{character_name}.json",
            "atlas": f"{character_name}.atlas",
            "texture": f"{character_name}.png"
        }
    }
    
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)
    
    return metadata_path


if __name__ == "__main__":
    print("Project packager module loaded successfully")

